#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

project_dir=$1
language=$2
git_init=${3:-true}
git_commit_start=${4:-false}

cd $project_dir
if [[ "$git_init" = true ]]; then
    cp --force "$SCRIPT_DIR/$language/assets/ignore/gitignore" ./.gitignore
    git init .
fi
if [[ "$git_commit_start" = true ]]; then
    git add .
    git commit -m 'Initial commit'
fi
