#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

project_name=$1
git_init=$2
git_commit_start=$3
project_dir=$4

if [[ "$git_init" = true ]]; then
    vcs=git
else
    vcs=none
fi

cd $project_dir
cargo init --vcs $vcs --name $project_name

cd "$SCRIPT_DIR/.."
./prepare_git $project_dir "rust" false $git_commit_start
