#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

project_name=$1
git_init=$2
git_commit_start=$3
project_dir=$4

echo "Setting up venv..."
cd $project_dir
python -m venv .venv

cd $SCRIPT_DIR/..
./prepare_git $project_dir "python" $git_init $git_commit_start
