#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

project_name=$1
git_init=$2
git_commit_start=$3
project_dir=$4

cd $project_dir
go mod init $project_name
go mod tidy

cd $SCRIPT_DIR/..
./prepare_git $project_dir $git_init $git_commit_start
