# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# "start-at-login" needs to be "true" for "after-login-command" to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# "after-startup-command" is run after "after-login-command"
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The "accordion-padding" specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = "tiles"

# Possible values: horizontal|vertical|auto
# "auto" means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = "auto"

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don"t like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don"t use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = "qwerty"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for "workspace-to-monitor-force-assignment".
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[mode.main.binding]
alt-slash = "layout tiles horizontal vertical"
alt-comma = "layout accordion horizontal vertical"

cmd-alt-h = "focus left"
cmd-alt-j = "focus down"
cmd-alt-k = "focus up"
cmd-alt-l = "focus right"

cmd-alt-f = "fullscreen --no-outer-gaps"
cmd-alt-m = "mode move"
cmd-alt-minus = "resize smart -50"
cmd-alt-equal = "resize smart +50"

cmd-alt-shift-r = "flatten-workspace-tree" # reset layout
cmd-alt-shift-f = "layout floating tiling" # toggle between tiling and floating

cmd-alt-1 = "workspace 1"
cmd-alt-2 = "workspace 2"
cmd-alt-3 = "workspace 3"
cmd-alt-4 = "workspace 4"
cmd-alt-5 = "workspace 5"
cmd-alt-6 = "workspace 6"
cmd-alt-7 = "workspace 7"
cmd-alt-8 = "workspace 8"
cmd-alt-9 = "workspace 9"

alt-tab = "focus-back-and-forth"

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ["layout sticky tiling", "mode main"]

[mode.move.binding]
esc = "mode main"

cmd-alt-h = [ "fullscreen off", "move left" ]
cmd-alt-j = [ "fullscreen off", "move down" ]
cmd-alt-k = [ "fullscreen off", "move up" ]
cmd-alt-l = [ "fullscreen off", "move right" ]

cmd-alt-shift-h = ["join-with left", "mode main"]
cmd-alt-shift-j = ["join-with down", "mode main"]
cmd-alt-shift-k = ["join-with up", "mode main"]
cmd-alt-shift-l = ["join-with right", "mode main"]

cmd-alt-1 = "move-node-to-workspace 1"
cmd-alt-2 = "move-node-to-workspace 2"
cmd-alt-3 = "move-node-to-workspace 3"
cmd-alt-4 = "move-node-to-workspace 4"
cmd-alt-5 = "move-node-to-workspace 5"
cmd-alt-6 = "move-node-to-workspace 6"
cmd-alt-7 = "move-node-to-workspace 7"
cmd-alt-8 = "move-node-to-workspace 8"
cmd-alt-9 = "move-node-to-workspace 9"

