# https://nikitabobko.github.io/AeroSpace/guide
# https://nikitabobko.github.io/AeroSpace/goodies
# https://nikitabobko.github.io/AeroSpace/commands

after-login-command = []
after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 20

default-root-container-layout = "tiles"

default-root-container-orientation = "auto"

on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = "qwerty"

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[mode.main.binding]
cmd-alt-t = [ "fullscreen off", "layout tiles horizontal vertical" ]
cmd-alt-c = [ "fullscreen off", "layout accordion horizontal vertical" ]

cmd-alt-h = [ "focus left", "move-mouse window-lazy-center" ]
cmd-alt-j = [ "focus down", "move-mouse window-lazy-center" ]
cmd-alt-k = [ "focus up", "move-mouse window-lazy-center" ]
cmd-alt-l = [ "focus right", "move-mouse window-lazy-center" ]

cmd-alt-f = "fullscreen --no-outer-gaps"
cmd-alt-shift-f = "macos-native-fullscreen"
cmd-alt-m = "mode move"
cmd-alt-w = "mode workspaces"
cmd-alt-minus = "resize smart -50"
cmd-alt-equal = "resize smart +50"

cmd-alt-shift-r = "flatten-workspace-tree" # reset layout
cmd-alt-shift-t = "layout floating tiling" # toggle between tiling and floating

cmd-alt-1 = "workspace 1"
cmd-alt-2 = "workspace 2"
cmd-alt-3 = "workspace 3"
cmd-alt-4 = "workspace 4"
cmd-alt-5 = "workspace 5"
cmd-alt-6 = "workspace 6"
cmd-alt-7 = "workspace 7"
cmd-alt-8 = "workspace 8"
cmd-alt-9 = "workspace 9"

alt-tab = "focus-back-and-forth"

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ["layout sticky tiling", "mode main"]

[mode.move.binding]
esc = "mode main"

h = [ "fullscreen off", "move left" ]
j = [ "fullscreen off", "move down" ]
k = [ "fullscreen off", "move up" ]
l = [ "fullscreen off", "move right" ]

shift-h = [ "join-with left"]
shift-j = [ "join-with down" ]
shift-k = [ "join-with up" ]
shift-l = [ "join-with right" ]

1 = [ "move-node-to-workspace 1", "mode main" ]
2 = [ "move-node-to-workspace 2", "mode main" ]
3 = [ "move-node-to-workspace 3", "mode main" ]
4 = [ "move-node-to-workspace 4", "mode main" ]
5 = [ "move-node-to-workspace 5", "mode main" ]
6 = [ "move-node-to-workspace 6", "mode main" ]
7 = [ "move-node-to-workspace 7", "mode main" ]
8 = [ "move-node-to-workspace 8", "mode main" ]
9 = [ "move-node-to-workspace 9", "mode main" ]

[mode.workspaces.binding]
esc = "mode main"
1 = [ "workspace 1", "mode main" ] # important, the default
p = [ "workspace P", "mode main" ] # programming
b = [ "workspace B", "mode main" ] # background
c = [ "workspace C", "mode main" ] # chat
m = [ "workspace M", "mode main" ] # misc

2 = [ "workspace 2", "mode main" ]
3 = [ "workspace 3", "mode main" ]
4 = [ "workspace 4", "mode main" ]
5 = [ "workspace 5", "mode main" ]
6 = [ "workspace 6", "mode main" ]
7 = [ "workspace 7", "mode main" ]
8 = [ "workspace 8", "mode main" ]
9 = [ "workspace 9", "mode main" ]
