#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
EXEC_DIR="$SCRIPT_DIR/../config"
cd $EXEC_DIR

relink () {
    local src=$1
    local dst=${2:-$1}

    rm -rf ~/.config/$dst 2> /dev/null
    ln -s "$(pwd)/"$src ~/.config/$dst
}
# function won't run in child shell without this
export -f relink


fd -t d -t f -d 1 -x bash -c 'relink {/}'

for APP in electron brave chromium chrome discord signal
do
    relink "electron-flags.conf" "$APP-flags.conf"
done

MIN_ELECTRON_VERSION=24
MAX_ELECTRON_VERSION=99
# Relink electron flags, because they're version-specific for some reason.
for ((i=1;i<=MIN_ELECTRON_VERSION;i++)) do
    relink "electron-flags-legacy.conf" "electron$i-flags.conf"
done
for ((i=$(( MIN_ELECTRON_VERSION + 1 ));i<=MAX_ELECTRON_VERSION;i++)) do
    relink "electron-flags.conf" "electron$i-flags.conf"
done

rm ~/.ideavimrc 2> /dev/null; ln -s "$(pwd)/ideavimrc" ~/.ideavimrc
rm ~/.gitconfig_global 2> /dev/null; ln -s "$(pwd)/gitconfig_global" ~/.gitconfig_global

cd - > /dev/null
