#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echoerr () { echo "$@" 1>&2; }

export -f echoerr

if [[ $# -gt 0 ]]; then
    project_name=$1
else
    while [[ -z ${project_name+x} ]] || [[ -z $project_name ]]; do
        read -p "Project name: " project_name
        project_name=$(echo $project_name | tr -d '[:space:]')
    done
fi


if [[ -d ~/projects/$project_name ]]; then
    echoerr "Project with the name $project_name exists"
    exit 1
fi

languages=$(fd . --type directory --exact-depth 1 "$SCRIPT_DIR/.project_init_languages" | xargs -I{} basename {})
if [[ -z $languages ]]; then
    echoerr "No languages"
    exit 2
fi

if [[ $# -gt 1 ]]; then
    language=$2
else
    language=$(echo "$languages" | fzf --height=~100% || :)
fi

# language not selected
if [[ -z $language ]]; then
    exit 0
fi

if [[ ! -d "$SCRIPT_DIR/.project_init_languages/$language" ]]; then
    echoerr "Invalid language: $language"
    echoerr "Available languages are:"
    echoerr "$languages"
    exit 1
fi

git_init=true
git_commit_start=true

"$SCRIPT_DIR"/.project_init_languages/prepare_directory "$language" "$HOME/projects/$project_name"
echo $project_name
echo $git_init
echo $git_commit_start
echo "$HOME/projects/$project_name"
"$SCRIPT_DIR"/.project_init_languages/$language/run $project_name $git_init $git_commit_start "$HOME/projects/$project_name"

tmux_join "$HOME/projects/$project_name"
