#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

export XDG_CURRENT_DESKTOP=sway
# export WLR_RENDERER=vulkan
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GDK_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export GTK_THEME Adwaita:dark
export WLR_NO_HARDWARE_CURSORS=1
export XWAYLAND_NO_GLAMOR=1

sway --unsupported-gpu
