#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . --min-depth 1 --max-depth 1 --type directory ~ ~/projects ~/study ~/dotfiles/config | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

# Handle running from bare terminal without tmux.
# Yes, this whole block is a dirty recursive hack.
# I don't care how bad this is, I just want it to work.
tmux_running=$(pgrep tmux)
if ! [[ -z $tmux_running ]]; then
    tmux new-session -s tmux_sessionizer "tmux_sessionizer $selected" > /dev/null
elif ! [[ -z $TMUX ]]; then
    tmux attach -x -t tmux_sessionizer 2> /dev/null
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
