#!/usr/bin/env bash

# We're inverting the return code,
# not the actual value of has-session here.
if [[ ! $(tmux has-session -t=$1 2> /dev/null) ]]; then
    if [[ "$1" = "/" ]]; then
        tmux new-session -ds $1 -c ~ 2> /dev/null
    else
        tmux new-session -ds $1 -c $1 2> /dev/null
    fi
fi

if [[ -n $TMUX ]]; then
    tmux switch-client -t $1 > /dev/null
else
    tmux attach-session -t $1 > /dev/null
fi
